name: Connect Experiment

on: push

jobs:
  build:

    name: Build Something

    runs-on: ubuntu-latest

    steps:
    
    - name: Setup Enclave
      uses: enclave-alistair/enclave-setup-action
      with:
        channel: unstable
        enrolment-key: ${{ secrets.ENCLAVE_ENROLMENT_KEY }}
        orgId: a09a8d4dd4ea4c12a33a51e3effac9fa
        apiKey: ${{ secrets.ENCLAVE_API_KEY }}
      
    - name: Wait for Connection to OnPrem
      run: enclave waitfor test-server-for-gh-setup.enclave

    - name: Query On-Premise Server
      run: curl http://test-server-for-gh-setup.enclave