name: Connect Experiment

on: push

jobs:
  build:

    name: Enclave Connectivity Test

    runs-on: ubuntu-latest

    steps:
    
    - name: Setup Enclave
      uses: enclave-alistair/enclave-setup-action@v1
      with:
        # The enrolment key we're using tags the runner with the 'gh-runner' tag, 
        # so connectivity happens automatically.
        enrolment-key: ${{ secrets.ENCLAVE_ENROLMENT_KEY }}
      
    - name: Wait for Connection to your on-prem server
      run: enclave waitfor on-prem-server.enclave

    - name: Query on-prem server
      run: curl on-prem-server.enclave
