name: Connect Experiment

on: push

jobs:
  build:

    name: Build Something

    runs-on: ubuntu-latest

    steps:

    - name: Enrol Enclave
      run: |
        curl -fsSL https://packages.enclave.io/apt/enclave.unstable.gpg | sudo apt-key add - 
        curl -fsSL https://packages.enclave.io/apt/enclave.unstable.list | sudo tee /etc/apt/sources.list.d/enclave.unstable.list
        sudo apt-get update
        sudo apt-get install enclave
        sudo enclave enrol ${{ secrets.ENCLAVE_ENROLMENT_KEY }}

    - name: Wait for Start      
      run: |
        enclave start -w
        enclave status
        ENCLAVE_ID=$(enclave status | grep "Local identity" | cut -d ' ' -f 3)
        ENCLAVE_ADDR=$(enclave status | grep "Local address" | cut -d ' ' -f 10)
        echo "::set-env name=ENCLAVE_ID::$ENCLAVE_ID"
        echo "::set-env name=ENCLAVE_ADDR::$ENCLAVE_ADDR"
        
    - name: Stop Enclave at End
      uses: webiny/action-post-run@2.0.1
      with:
        run: enclave stop
        
    - name: Revoke Enrolled System at End
      uses: webiny/action-post-run@2.0.1
      with:
        run: curl --oauth2-bearer ${{ secrets.ENCLAVE_API_KEY }} -X DELETE https://api.enclave.io/org/ae7e35a160104a9f831ff5b9422b59e0/systems/$ENCLAVE_ID
      
    - name: Configure DNS
      run: |
        echo "DNS=$ENCLAVE_ADDR" | sudo tee -a /etc/systemd/resolved.conf
        sudo systemctl restart systemd-resolved    

        resolvectl status

        sleep 5
      
    - name: Print Logs
      run: |
        cat /var/log/enclave/*

    - name: Query On-Premise Server
      run: curl http://on-prem-build-server.enclave