name: Connect Experiment

on: push

jobs:
  build:

    name: Build Something

    runs-on: ubuntu-latest

    steps:

    - name: Enrol Enclave
      run: |
        curl -fsSL https://packages.enclave.io/apt/enclave.unstable.gpg | sudo apt-key add - 
        curl -fsSL https://packages.enclave.io/apt/enclave.unstable.list | sudo tee /etc/apt/sources.list.d/enclave.unstable.list
        sudo apt-get update
        sudo apt-get install enclave
        sudo enclave enrol ${{ secrets.ENCLAVE_ENROLMENT_KEY }}       

    - name: Wait for Start
      run: |
        enclave start -w
        enclave status
      
    - name: Configure DNS
      run: |
        cat /etc/resolv.conf
        VIRT_ADDR=$(enclave status | grep "Local address" | cut -d ' ' -f 10)
        echo "DNS=$VIRT_ADDR" | sudo tee -a /etc/systemd/resolved.conf
        sudo systemctl restart systemd-resolved    
        cat /etc/resolv.conf

        resolvectl status

        sleep 5
        
        resolvectl status
        

    - name: Query On-Premise Server
      run: curl http://on-prem-build-server.enclave